# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@2.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  checking:
    docker:
      - image: cimg/ruby:3.0.1
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          format: progress
          label: Inspecting with Rubocop
  test:
    docker:
      - image: cimg/ruby:3.0.1
      - environment:
          POSTGRES_DB: circle_ci_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circle_test_user
        image: cimg/postgres:14.5
    parallelism: 3
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: '127.0.0.1'
      PGPASSWORD: ''
      PGUSER: circle_test_user
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: 'Wait for db'
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database create
          command: bundle exec rails db:create
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - checking
      - test:
          requires:
            - checking
