default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: circle_test_development

test:
  <<: *default
  database: circle_test_test

staging:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %>
